import type { Metadata } from "next"
import { Poppins } from "next/font/google"
import { auth } from "@/auth"
import { SessionProvider } from "next-auth/react"
import "./global.css"
import Navbar from "@/components/navbar/Navbar"
import { Toaster } from "react-hot-toast"

const poppins = Poppins(
  {
    weight: "400",
    subsets: ['latin'],
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={poppins.className}>
          <Navbar />
          <Toaster containerStyle={{ top: 70 }} />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
